### ISSUE TITLE
Update documentation link/methodology on crossplane.io, and fix broken links

### ISSUE THREAD

**Issue by robsclark** [crossplane/crossplane.github.io#23]
Crossplane.io - documentation

Defaults to "Crossplane v0.2 latest" in the pull down menu

Most docs have been updated in Master

When you select master you get a red warning box that is off putting

Suggestion is to:

1. Remove the warning box
2. Make the default the latest docs (not sure if we call that master or give it a generic name, like "latest" if master is off-putting
3. Tag the docs in master with the TOC/positon information eg (https://images.zenhubusercontent.com/5cd3396068f236637fc7f614/c3da11cb-dfb6-4169-af17-0779cdae8b9e)

The goal is for the documentation menu dropdown to default to the latest, have those docs auto-reference from master, without the warning screens.

In exploring the issue, some documentation links are broken.

**Comment by jbw976** [comment]
Thanks for opening this issue @robsclark! I agree with you that the current docs approach is a bit off-putting, but I have concerns about defaulting to master.  We had significant issues in the Rook project with defaulting the docs to master because there is no stability or consistency guarantees with the master docs, you only get that with the official releases.  We ended up with a large support load from folks using features directly from master followed by later changes before the next release causing incompatible breaking changes.  It was quite a headache.

That may be different for the Crossplane project and where it currently is right now though, so I'm open to more discussion.  I think the real issue here is that the release cadence of Crossplane has been behind where we want it to be, we need to have more frequent releases.  IT has been way too long since v0.2 and that is definitely something we will fix going forward, I expect v0.4 and v0.5 to be at a more rapid pace of release.

What do you think of the following?
* The red warning box is intimidating, let's tone that down so it's not as in your face and scary, but still does deliver a message about stability of master
* Increase the frequency of releases so that the current defaulting of most recent official release is actually a good and up to date experience.

Thoughts? Happy to sync up offline and summarize here for the community :)

**Comment by jbw976** [comment]
Synced up with @robsclark and the short term fix we'd like to accomplish is to update the master branch warning message box to:

* streamline the messaging, down to a single sentence?
* update the color, font, etc. to make it less intense and more friendly

In the long term, we will be making a big docs push before v0.3 and we will increase the release frequency to keep the most recent official docs more up to date.

Sound good @thephred?

**Comment by thephred** [comment]
@jbw976 sounds great

**Comment by thephred** [comment]
@jbw976 said this is no longer an issue so I will close this.
